[package]
name = "rust_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
minifb = "0.24.0"
noise = "0.8.0"
euclid = "0.22.9"
flo_curves = "0.7.2"